/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Controlador.ControladorCarton;
import Controlador.ControladorPrincipal;
import Controlador.ControladorTombola;
import Modelo.Carton;
import java.awt.Color;
import static java.awt.Color.WHITE;
import static java.awt.Color.YELLOW;
import java.util.HashSet;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Luisk
 */
public class FrmJuego extends javax.swing.JFrame {

    private final ControladorPrincipal contrlPrin = new ControladorPrincipal();
    private final ControladorCarton contrlCart = new ControladorCarton();
    private final ControladorTombola contrlTomb = new ControladorTombola();
    private boolean tipoCarton = true;
    private HashSet<FrmCarton> frmCartones = new HashSet();
    /**
     * Creates new form FrmJuego
     */
    public FrmJuego() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopJuego = new javax.swing.JDesktopPane();
        imgCarton = new javax.swing.JLabel();
        imgBolas = new javax.swing.JLabel();
        imgFicha = new javax.swing.JLabel();
        btnManual = new javax.swing.JButton();
        btnAgregarCarton = new javax.swing.JButton();
        ComboCartones = new javax.swing.JComboBox<>();
        btnIniciar = new javax.swing.JButton();
        btnAutomatico = new javax.swing.JButton();
        btnCantidadCartones = new javax.swing.JButton();
        btnSeleccionarModo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnAgregarCarton1 = new javax.swing.JButton();
        btnAgregarCarton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        DesktopJuego.setBackground(new java.awt.Color(153, 153, 153));

        imgCarton.setBackground(new java.awt.Color(153, 153, 153));
        imgCarton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bingo.png"))); // NOI18N
        imgCarton.setOpaque(true);

        imgBolas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/videobingo-slots-header.png"))); // NOI18N

        imgFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ficha-de-casino.png"))); // NOI18N

        btnManual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnManual.setText("Manual");
        btnManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualActionPerformed(evt);
            }
        });

        btnAgregarCarton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregarCarton.setText("Agregar");
        btnAgregarCarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCartonActionPerformed(evt);
            }
        });

        ComboCartones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        ComboCartones.setToolTipText("");
        ComboCartones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCartonesActionPerformed(evt);
            }
        });

        btnIniciar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIniciar.setText("Iniciar Juego");

        btnAutomatico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAutomatico.setText("Automatico");
        btnAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomaticoActionPerformed(evt);
            }
        });

        btnCantidadCartones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCantidadCartones.setText("Cantidad de Cartones:");
        btnCantidadCartones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantidadCartonesActionPerformed(evt);
            }
        });

        btnSeleccionarModo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSeleccionarModo.setText("Selecciona el Modo:");
        btnSeleccionarModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarModoActionPerformed(evt);
            }
        });

        btnAgregarCarton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregarCarton1.setText("Último Número:");
        btnAgregarCarton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCarton1ActionPerformed(evt);
            }
        });

        btnAgregarCarton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregarCarton2.setText("Número");
        btnAgregarCarton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCarton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(btnAgregarCarton2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarCarton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarCarton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarCarton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(266, Short.MAX_VALUE))
        );

        DesktopJuego.setLayer(imgCarton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(imgBolas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(imgFicha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(btnManual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(btnAgregarCarton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(ComboCartones, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(btnIniciar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(btnAutomatico, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(btnCantidadCartones, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(btnSeleccionarModo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopJuegoLayout = new javax.swing.GroupLayout(DesktopJuego);
        DesktopJuego.setLayout(DesktopJuegoLayout);
        DesktopJuegoLayout.setHorizontalGroup(
            DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopJuegoLayout.createSequentialGroup()
                .addGap(0, 593, Short.MAX_VALUE)
                .addComponent(imgBolas)
                .addGap(296, 296, 296)
                .addComponent(imgFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopJuegoLayout.createSequentialGroup()
                .addGroup(DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DesktopJuegoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnSeleccionarModo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnManual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAutomatico))
                    .addGroup(DesktopJuegoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(imgCarton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(DesktopJuegoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DesktopJuegoLayout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(DesktopJuegoLayout.createSequentialGroup()
                                    .addComponent(btnCantidadCartones, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(ComboCartones, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnAgregarCarton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DesktopJuegoLayout.setVerticalGroup(
            DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopJuegoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgBolas, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgCarton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManual, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionarModo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboCartones, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarCarton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCantidadCartones, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopJuego, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DesktopJuego)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int r = JOptionPane.showConfirmDialog(this, "¿Desea volver a la página principal?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if (r == JOptionPane.YES_OPTION) {
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }else{
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnAgregarCartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCartonActionPerformed
        String id=null;
        int veces = ComboCartones.getSelectedIndex() + 1;
        for (int i = 0; i < veces; i++) {
        if (this.tipoCarton) {   
            id =this.contrlPrin.agregarCartonAutomatico();
        }else{
            id =this.contrlPrin.agregarCartonManual();
        }
            Carton carton = this.contrlPrin.buscarCarton(id);
            FrmCarton nuevoCarton = new FrmCarton(this.contrlPrin);
            nuevoCarton.llenarCarton(carton.getNumeros(), id);
            this.DesktopJuego.add(nuevoCarton);
            nuevoCarton.setVisible(true);
        
        }
    }//GEN-LAST:event_btnAgregarCartonActionPerformed

    private void btnManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualActionPerformed

        btnManual.setEnabled(false);
        btnAutomatico.setEnabled(true);
        this.tipoCarton = false;
    }//GEN-LAST:event_btnManualActionPerformed

    private void btnAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomaticoActionPerformed
        
        btnManual.setEnabled(true);
        btnAutomatico.setEnabled(false);
        this.tipoCarton = true;
    }//GEN-LAST:event_btnAutomaticoActionPerformed

    private void ComboCartonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCartonesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboCartonesActionPerformed

    private void btnCantidadCartonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantidadCartonesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCantidadCartonesActionPerformed

    private void btnSeleccionarModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarModoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarModoActionPerformed

    private void btnAgregarCarton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCarton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarCarton1ActionPerformed

    private void btnAgregarCarton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCarton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarCarton2ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCartones;
    private javax.swing.JDesktopPane DesktopJuego;
    private javax.swing.JButton btnAgregarCarton;
    private javax.swing.JButton btnAgregarCarton1;
    private javax.swing.JButton btnAgregarCarton2;
    private javax.swing.JButton btnAutomatico;
    private javax.swing.JButton btnCantidadCartones;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnManual;
    private javax.swing.JButton btnSeleccionarModo;
    private javax.swing.JLabel imgBolas;
    private javax.swing.JLabel imgCarton;
    private javax.swing.JLabel imgFicha;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
