/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;


import Controlador.ControladorJuego;
import Modelo.Carton;
import Modelo.ModoJuego;
import java.util.HashSet;
import java.util.List;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Luisk
 */
public class FrmJuego extends javax.swing.JFrame {
    private boolean modoAutomatico = false; 
    private boolean juegoIniciado = false;
    private final ControladorJuego contrlPrin = new ControladorJuego();
    private boolean tipoCarton = true; 
    private HashSet<FrmCarton> frmCartones = new HashSet<>();
    private final FrmTableroo frmTablero = new FrmTableroo();
    private int numeroActual = -1;
    private int numeroAnterior = -1;
    /**
     * Creates new form FrmJuego
     */
    public FrmJuego() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        desactivarTodo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        DesktopJuego = new javax.swing.JDesktopPane();
        imgFicha = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnIniciar = new javax.swing.JButton();
        rbtManualJuego = new javax.swing.JRadioButton();
        rbtAutomaticoJuego = new javax.swing.JRadioButton();
        btnSeleccionarModo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAutomatico = new javax.swing.JButton();
        btnManual = new javax.swing.JButton();
        btnAgregarCarton = new javax.swing.JButton();
        lblCartones = new javax.swing.JLabel();
        panelTombola = new javax.swing.JPanel();
        btnSacar = new javax.swing.JButton();
        BtnNumeroCantado = new javax.swing.JButton();
        btnSacarManual = new javax.swing.JButton();
        txtNumeroManual = new javax.swing.JTextField();
        lblTombola = new javax.swing.JLabel();
        btnDesmarcar = new javax.swing.JButton();
        txtDesmarcar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        DesktopJuego.setBackground(new java.awt.Color(51, 0, 0));
        DesktopJuego.setEnabled(false);

        imgFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ficha-de-casino.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 175, 55)));

        btnIniciar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIniciar.setText("Iniciar Juego");
        btnIniciar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtManualJuego);
        rbtManualJuego.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtManualJuego.setText("Manual");
        rbtManualJuego.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rbtManualJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtManualJuegoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtAutomaticoJuego);
        rbtAutomaticoJuego.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rbtAutomaticoJuego.setText("Automatico");
        rbtAutomaticoJuego.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSeleccionarModo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSeleccionarModo.setText("Modo de juego");
        btnSeleccionarModo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 175, 55)));
        btnSeleccionarModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarModoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("       Configurar Juego");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtManualJuego)
                            .addComponent(rbtAutomaticoJuego)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnSeleccionarModo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSeleccionarModo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtManualJuego)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtAutomaticoJuego))
                    .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 175, 55)));

        btnAutomatico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAutomatico.setText("Automatico");
        btnAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomaticoActionPerformed(evt);
            }
        });

        btnManual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnManual.setText("Manual");
        btnManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualActionPerformed(evt);
            }
        });

        btnAgregarCarton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregarCarton.setText("Agregar Carton");
        btnAgregarCarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCartonActionPerformed(evt);
            }
        });

        lblCartones.setBackground(new java.awt.Color(51, 51, 51));
        lblCartones.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        lblCartones.setForeground(new java.awt.Color(255, 255, 255));
        lblCartones.setText("         Cartones");
        lblCartones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblCartones.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnManual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAutomatico)
                .addGap(16, 16, 16))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnAgregarCarton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCartones, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCartones, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManual, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarCarton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelTombola.setBackground(new java.awt.Color(51, 51, 51));
        panelTombola.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 175, 55), 2));

        btnSacar.setBackground(new java.awt.Color(212, 175, 55));
        btnSacar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSacar.setForeground(new java.awt.Color(0, 0, 0));
        btnSacar.setText("Generar");
        btnSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarActionPerformed(evt);
            }
        });

        BtnNumeroCantado.setBackground(new java.awt.Color(212, 175, 55));
        BtnNumeroCantado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtnNumeroCantado.setForeground(new java.awt.Color(0, 0, 0));
        BtnNumeroCantado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNumeroCantadoActionPerformed(evt);
            }
        });

        btnSacarManual.setBackground(new java.awt.Color(212, 175, 55));
        btnSacarManual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSacarManual.setForeground(new java.awt.Color(0, 0, 0));
        btnSacarManual.setText("Sacar numero");
        btnSacarManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarManualActionPerformed(evt);
            }
        });

        txtNumeroManual.setBackground(new java.awt.Color(51, 0, 0));
        txtNumeroManual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNumeroManual.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNumeroManual.setEnabled(false);
        txtNumeroManual.setOpaque(true);
        txtNumeroManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroManualActionPerformed(evt);
            }
        });

        lblTombola.setBackground(new java.awt.Color(51, 51, 51));
        lblTombola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTombola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rueda.png"))); // NOI18N
        lblTombola.setOpaque(true);

        btnDesmarcar.setBackground(new java.awt.Color(212, 175, 55));
        btnDesmarcar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDesmarcar.setForeground(new java.awt.Color(0, 0, 0));
        btnDesmarcar.setText("Desmarcar numero");
        btnDesmarcar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDesmarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesmarcarActionPerformed(evt);
            }
        });

        txtDesmarcar.setBackground(new java.awt.Color(51, 0, 0));
        txtDesmarcar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDesmarcar.setForeground(new java.awt.Color(255, 255, 255));
        txtDesmarcar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtDesmarcar.setEnabled(false);
        txtDesmarcar.setOpaque(true);
        txtDesmarcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesmarcarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTombolaLayout = new javax.swing.GroupLayout(panelTombola);
        panelTombola.setLayout(panelTombolaLayout);
        panelTombolaLayout.setHorizontalGroup(
            panelTombolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTombola, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTombolaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTombolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSacarManual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDesmarcar, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(panelTombolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BtnNumeroCantado, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(txtNumeroManual)
                    .addComponent(txtDesmarcar))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelTombolaLayout.setVerticalGroup(
            panelTombolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTombolaLayout.createSequentialGroup()
                .addComponent(lblTombola, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTombolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSacar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnNumeroCantado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTombolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacarManual, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroManual, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTombolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDesmarcar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesmarcar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BingoBanner.png"))); // NOI18N

        btnReiniciar.setBackground(new java.awt.Color(51, 51, 51));
        btnReiniciar.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnReiniciar.setText("Reiniciar juego");
        btnReiniciar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 175, 55)));
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ficha-de-casino.png"))); // NOI18N

        DesktopJuego.setLayer(imgFicha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(panelTombola, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(btnReiniciar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopJuegoLayout = new javax.swing.GroupLayout(DesktopJuego);
        DesktopJuego.setLayout(DesktopJuegoLayout);
        DesktopJuegoLayout.setHorizontalGroup(
            DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopJuegoLayout.createSequentialGroup()
                .addGroup(DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DesktopJuegoLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DesktopJuegoLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DesktopJuegoLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(panelTombola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84)
                .addGroup(DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(imgFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DesktopJuegoLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DesktopJuegoLayout.createSequentialGroup()
                        .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        DesktopJuegoLayout.setVerticalGroup(
            DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopJuegoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DesktopJuegoLayout.createSequentialGroup()
                        .addGroup(DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(DesktopJuegoLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panelTombola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))
                            .addGroup(DesktopJuegoLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 191, Short.MAX_VALUE))
                    .addGroup(DesktopJuegoLayout.createSequentialGroup()
                        .addGroup(DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopJuego)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(DesktopJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void actualizarCartonesConNumero(int numero) {
        for (FrmCarton frm : frmCartones) {
            frm.pintarCarton(numero);
        }
    }
    private void reproducirSonido(String ruta) {
    try {
        AudioInputStream audioIn = AudioSystem.getAudioInputStream(
            getClass().getResource(ruta)
        );
        Clip clip = AudioSystem.getClip();
        clip.open(audioIn);
        clip.start();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, 
            "No se pudo reproducir el audio.", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }
}
    private void configurarModoDeJuego() {
    rbtManualJuego.setEnabled(false);
    rbtAutomaticoJuego.setEnabled(false);
    btnAgregarCarton.setEnabled(true);
    btnDesmarcar.setEnabled(true);
    txtDesmarcar.setEnabled(true);
    btnReiniciar.setEnabled(true);
    if (!modoAutomatico) {
      BtnNumeroCantado.setEnabled(true);
        tipoCarton = false;

        btnManual.setEnabled(false);      
        btnAutomatico.setEnabled(true);   
        txtNumeroManual.setEnabled(true);
        btnSacarManual.setEnabled(true);

        btnSacar.setEnabled(false);
    }

   
    else {
      BtnNumeroCantado.setEnabled(true);
        
        tipoCarton = true;
        txtDesmarcar.setEnabled(true);
        btnDesmarcar.setEnabled(true);
        btnAutomatico.setEnabled(false);
        btnManual.setEnabled(true);       

        txtNumeroManual.setEnabled(false);
        btnSacarManual.setEnabled(false);

        btnSacar.setEnabled(true);
    }
}
    private void desactivarFuncionesDelJuego() {

    btnAgregarCarton.setEnabled(false);
    btnManual.setEnabled(false);
    btnAutomatico.setEnabled(false);

    btnSacar.setEnabled(false);

    txtNumeroManual.setEnabled(false);
    btnSacarManual.setEnabled(false);

    btnDesmarcar.setEnabled(false);

    btnReiniciar.setEnabled(true); 
    buttonGroup1.clearSelection();
}
    private void desactivarTodo() {

    btnAgregarCarton.setEnabled(false);
    btnDesmarcar.setEnabled(false);
    btnReiniciar.setEnabled(false);
    btnSeleccionarModo.setEnabled(false);

    btnSacar.setEnabled(false);
    btnSacarManual.setEnabled(false);
    BtnNumeroCantado.setEnabled(false);

    txtNumeroManual.setEnabled(false);

    btnManual.setEnabled(false);
    btnAutomatico.setEnabled(false);

    txtDesmarcar.setEnabled(false);

    BtnNumeroCantado.setText("Último Número:");
}
    private void verificarGanadores() {
        List<Carton> cartones = contrlPrin.listarCartones();
        StringBuilder ganadores = new StringBuilder();

        for (Carton c : cartones) {
            if (contrlPrin.esGanador(c)) {
                ganadores.append("Cartón ID: ").append(c.getId()).append("\n");
            }
        }
       
        if (ganadores.length() > 0) {
            reproducirSonido("/sonidos/a12668a8.wav");
            JOptionPane.showMessageDialog(
                this,
                "¡TENEMOS GANADOR(ES)!\n\n" + ganadores,
                "Ganador",
                JOptionPane.INFORMATION_MESSAGE
            );
        }
    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int r = JOptionPane.showConfirmDialog(this, "¿Desea volver a la página principal?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if (r == JOptionPane.YES_OPTION) {
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }else{
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnAgregarCartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCartonActionPerformed
      
        if (!juegoIniciado) {
    JOptionPane.showMessageDialog(this,
        "Debe iniciar el juego antes.",
        "Advertencia",
        JOptionPane.WARNING_MESSAGE
    );
    return;
}
        String id;

    if (tipoCarton) {
        id = contrlPrin.agregarCartonAutomatico();
    } else {
        id = contrlPrin.agregarCartonManual();
    }

    Carton carton = contrlPrin.buscarCarton(id);

    FrmCarton nuevoCarton = new FrmCarton(contrlPrin);
    DesktopJuego.add(nuevoCarton);

    if (tipoCarton) {
        nuevoCarton.llenarCarton(carton.getNumeros(), id);
    } 
    else {
        nuevoCarton.habilitarModoManual();
        nuevoCarton.setId(id); 
    }

   
    nuevoCarton.setVisible(true);

   
    contrlPrin.registrarObserver(nuevoCarton);

    frmCartones.add(nuevoCarton);

    }//GEN-LAST:event_btnAgregarCartonActionPerformed

    private void btnManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualActionPerformed
       
        btnManual.setEnabled(false);
        btnAutomatico.setEnabled(true);
        this.tipoCarton = false;
    }//GEN-LAST:event_btnManualActionPerformed

    private void btnAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomaticoActionPerformed
        
        btnManual.setEnabled(true);
        btnAutomatico.setEnabled(false);
        this.tipoCarton = true;
    }//GEN-LAST:event_btnAutomaticoActionPerformed

    private void btnSeleccionarModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarModoActionPerformed
        String[] opciones = { "Normal", "Cuatro esquinas", "Cartón lleno" };

        String seleccion = (String) JOptionPane.showInputDialog(
            this,
            "Seleccione el modo de juego:",
            "Modo de juego",
            JOptionPane.PLAIN_MESSAGE,
            null,
            opciones,
            opciones[0]
        );

        if (seleccion == null) return;

        switch (seleccion) {
            case "Normal" ->
                contrlPrin.setModo(ModoJuego.NORMAL);
            case "Cuatro esquinas" ->
                contrlPrin.setModo(ModoJuego.CUATRO_ESQUINAS);
            case "Cartón lleno" ->
                contrlPrin.setModo(ModoJuego.CARTON_LLENO);
        }

        JOptionPane.showMessageDialog(this, "Modo de juego seleccionado: " + seleccion);
    }//GEN-LAST:event_btnSeleccionarModoActionPerformed

    private void BtnNumeroCantadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNumeroCantadoActionPerformed
         int ultimo = contrlPrin.getUltimoNumero();

        if (ultimo == -1) {
            JOptionPane.showMessageDialog(this, "Todavía no se ha cantado ningún número.");
        } else {
            JOptionPane.showMessageDialog(this, ultimo);
        }
    }//GEN-LAST:event_BtnNumeroCantadoActionPerformed

    private void btnSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarActionPerformed
if (frmCartones.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Debe agregar al menos un cartón antes de sacar un número.",
            "Advertencia",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    int numero = contrlPrin.sacarNumeroAuto();
    if (numero == -1) {
        JOptionPane.showMessageDialog(this, "Ya no hay más números disponibles.");
        return;
    }

    if (numeroActual != -1) {
        numeroAnterior = numeroActual;
        frmTablero.marcarNumeroAnterior(numeroActual);
    }

    numeroActual = numero;
    frmTablero.marcarNumeroActual(numero);

    BtnNumeroCantado.setText(String.valueOf(numero));
    verificarGanadores();
    }//GEN-LAST:event_btnSacarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
      reproducirSonido("/sonidos/7bd17b0b.wav");
    
    if (!rbtManualJuego.isSelected() && !rbtAutomaticoJuego.isSelected()) {
        JOptionPane.showMessageDialog(this,
            "Debe seleccionar si el juego será Manual o Automático.",
            "Atención",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }

   
    modoAutomatico = rbtAutomaticoJuego.isSelected();
    juegoIniciado = true;

    
    if (modoAutomatico) {

        tipoCarton = true;

        btnAutomatico.setEnabled(false);  
        btnManual.setEnabled(true);       
    } else {
        
        tipoCarton = false;

        btnManual.setEnabled(false);      
        btnAutomatico.setEnabled(true);   
    }
    configurarModoDeJuego();
    btnSeleccionarModo.setEnabled(true);

    JOptionPane.showMessageDialog(this,
        "Juego iniciado en modo " + (modoAutomatico ? "Automático" : "Manual") + ".",
        "Listo!",
        JOptionPane.INFORMATION_MESSAGE
    );

    if (frmTablero.getParent() == null) {
        DesktopJuego.add(frmTablero);
        frmTablero.pack();
        frmTablero.setBounds(600, 20, 500, 700);
        frmTablero.setVisible(true);
        contrlPrin.registrarObserver(frmTablero); 
    }

    BtnNumeroCantado.setText("Último Número:");
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnSacarManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarManualActionPerformed
       if (frmCartones.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Debe agregar al menos un cartón antes de sacar un número.",
            "Advertencia",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    String txt = txtNumeroManual.getText().trim();
    if (txt.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese un número.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        int n = Integer.parseInt(txt);

        boolean ok = contrlPrin.ingresarManual(n);
        if (!ok) {
            JOptionPane.showMessageDialog(this,
                "Número inválido, fuera de rango, o ya salió.",
                "Error", JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        if (numeroActual != -1) {
            numeroAnterior = numeroActual;
            frmTablero.marcarNumeroAnterior(numeroActual);
        }

        numeroActual = n;
        frmTablero.marcarNumeroActual(n);

        BtnNumeroCantado.setText(String.valueOf(n));
        verificarGanadores();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
            "Debe escribir un número válido.",
            "Error", JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnSacarManualActionPerformed

    private void txtNumeroManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroManualActionPerformed

    private void btnDesmarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesmarcarActionPerformed
      
    if (!juegoIniciado) {
        JOptionPane.showMessageDialog(this,
            "Debe iniciar el juego antes.",
            "Advertencia",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    String txt = txtDesmarcar.getText().trim();

    if (txt.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese un número.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        int n = Integer.parseInt(txt);

        contrlPrin.desmarcarNumero(n);

   
        for (FrmCarton frm : frmCartones) {
            frm.DesmarcarCarton(n);
        }

        frmTablero.desmarcarNumero(n);

        if (numeroActual == n) {
            numeroActual = -1;
            BtnNumeroCantado.setText("Último Número:");
        }

        if (numeroAnterior == n) {
            numeroAnterior = -1;
        }

        JOptionPane.showMessageDialog(this, "Número desmarcado.");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Debe ser un número válido.");
    }
    }//GEN-LAST:event_btnDesmarcarActionPerformed

    private void txtDesmarcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesmarcarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesmarcarActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
      if (!juegoIniciado) {
        JOptionPane.showMessageDialog(this,
            "Debe iniciar el juego antes.",
            "Advertencia",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    btnSeleccionarModo.setEnabled(false);

    contrlPrin.reiniciarJuegoCompleto();

    for (FrmCarton frm : frmCartones) {
        frm.dispose(); 
    }
    frmCartones.clear(); 
   
    if (frmTablero != null) {
        frmTablero.limpiarTablero();
    }

    BtnNumeroCantado.setText("Último Número:");

    rbtManualJuego.setEnabled(true);
    rbtAutomaticoJuego.setEnabled(true);

    desactivarFuncionesDelJuego();

    juegoIniciado = false;
    buttonGroup1.clearSelection();

    JOptionPane.showMessageDialog(this,
        "Juego reiniciado. Seleccione nuevamente si jugará Manual o Automático.",
        "Reiniciado",
        JOptionPane.INFORMATION_MESSAGE
    );

    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void rbtManualJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtManualJuegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtManualJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNumeroCantado;
    private javax.swing.JDesktopPane DesktopJuego;
    private javax.swing.JButton btnAgregarCarton;
    private javax.swing.JButton btnAutomatico;
    private javax.swing.JButton btnDesmarcar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnManual;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnSacar;
    private javax.swing.JButton btnSacarManual;
    private javax.swing.JButton btnSeleccionarModo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel imgFicha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCartones;
    private javax.swing.JLabel lblTombola;
    private javax.swing.JPanel panelTombola;
    private javax.swing.JRadioButton rbtAutomaticoJuego;
    private javax.swing.JRadioButton rbtManualJuego;
    private javax.swing.JTextField txtDesmarcar;
    private javax.swing.JTextField txtNumeroManual;
    // End of variables declaration//GEN-END:variables
}
