/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;


import Controlador.ControladorJuego;
import Modelo.Carton;
import Modelo.ModoJuego;
import java.util.HashSet;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Luisk
 */
public class FrmJuego extends javax.swing.JFrame {

    private final ControladorJuego contrlPrin = new ControladorJuego();
    private boolean tipoCarton = true; 
    private HashSet<FrmCarton> frmCartones = new HashSet<>();
    private final FrmTableroo frmTablero = new FrmTableroo();

    /**
     * Creates new form FrmJuego
     */
    public FrmJuego() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopJuego = new javax.swing.JDesktopPane();
        imgCarton = new javax.swing.JLabel();
        imgBolas = new javax.swing.JLabel();
        imgFicha = new javax.swing.JLabel();
        btnManual = new javax.swing.JButton();
        btnAgregarCarton = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        btnAutomatico = new javax.swing.JButton();
        btnSeleccionarModo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnAgregarCarton1 = new javax.swing.JButton();
        btnAgregarCarton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        DesktopJuego.setBackground(new java.awt.Color(153, 153, 153));

        imgCarton.setBackground(new java.awt.Color(153, 153, 153));
        imgCarton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bingo.png"))); // NOI18N
        imgCarton.setOpaque(true);

        imgBolas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/videobingo-slots-header.png"))); // NOI18N

        imgFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ficha-de-casino.png"))); // NOI18N

        btnManual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnManual.setText("Manual");
        btnManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManualActionPerformed(evt);
            }
        });

        btnAgregarCarton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregarCarton.setText("Agregar Carton");
        btnAgregarCarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCartonActionPerformed(evt);
            }
        });

        btnIniciar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIniciar.setText("Iniciar Juego");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnAutomatico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAutomatico.setText("Automatico");
        btnAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutomaticoActionPerformed(evt);
            }
        });

        btnSeleccionarModo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSeleccionarModo.setText("Selecciona el Modo:");
        btnSeleccionarModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarModoActionPerformed(evt);
            }
        });

        btnAgregarCarton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregarCarton1.setText("Último Número:");
        btnAgregarCarton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCarton1ActionPerformed(evt);
            }
        });

        btnAgregarCarton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregarCarton2.setText("Número");
        btnAgregarCarton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCarton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(btnAgregarCarton2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarCarton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarCarton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarCarton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(266, Short.MAX_VALUE))
        );

        DesktopJuego.setLayer(imgCarton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(imgBolas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(imgFicha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(btnManual, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(btnAgregarCarton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(btnIniciar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(btnAutomatico, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(btnSeleccionarModo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DesktopJuego.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopJuegoLayout = new javax.swing.GroupLayout(DesktopJuego);
        DesktopJuego.setLayout(DesktopJuegoLayout);
        DesktopJuegoLayout.setHorizontalGroup(
            DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopJuegoLayout.createSequentialGroup()
                .addGap(0, 593, Short.MAX_VALUE)
                .addComponent(imgBolas)
                .addGap(296, 296, 296)
                .addComponent(imgFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(DesktopJuegoLayout.createSequentialGroup()
                .addGroup(DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DesktopJuegoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(imgCarton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(DesktopJuegoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DesktopJuegoLayout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(238, 238, 238)))
                    .addGroup(DesktopJuegoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnSeleccionarModo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnManual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAutomatico))
                    .addGroup(DesktopJuegoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarCarton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DesktopJuegoLayout.setVerticalGroup(
            DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopJuegoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgBolas, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgCarton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnManual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DesktopJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAutomatico, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSeleccionarModo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarCarton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 19, Short.MAX_VALUE)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopJuego, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(DesktopJuego)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void actualizarCartonesConNumero(int numero) {
        for (FrmCarton frm : frmCartones) {
            frm.pintarCarton(numero);
        }
    }

    private void verificarGanadores() {
        List<Carton> cartones = contrlPrin.listarCartones();
        StringBuilder ganadores = new StringBuilder();

        for (Carton c : cartones) {
            if (contrlPrin.esGanador(c)) {
                ganadores.append("Cartón ID: ").append(c.getId()).append("\n");
            }
        }

        if (ganadores.length() > 0) {
            JOptionPane.showMessageDialog(
                this,
                "¡TENEMOS GANADOR(ES)!\n\n" + ganadores,
                "Ganador",
                JOptionPane.INFORMATION_MESSAGE
            );
        }
    }
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int r = JOptionPane.showConfirmDialog(this, "¿Desea volver a la página principal?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if (r == JOptionPane.YES_OPTION) {
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }else{
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnAgregarCartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCartonActionPerformed
      String id;

    if (tipoCarton) {
        id = contrlPrin.agregarCartonAutomatico();
    } else {
        id = contrlPrin.agregarCartonManual();
    }

    Carton carton = contrlPrin.buscarCarton(id);

    // Crear la ventana del cartón
    FrmCarton nuevoCarton = new FrmCarton(contrlPrin);
    DesktopJuego.add(nuevoCarton);

    // --- AUTO ---
    if (tipoCarton) {
        nuevoCarton.llenarCarton(carton.getNumeros(), id);
    } 
    // --- MANUAL ---
    else {
        nuevoCarton.habilitarModoManual();
        nuevoCarton.setId(id); 
    }

    // Mostrarlo
    nuevoCarton.setVisible(true);

    // Registrar observer UNA VEZ
    contrlPrin.registrarObserver(nuevoCarton);

    // Guardarlo
    frmCartones.add(nuevoCarton);

    }//GEN-LAST:event_btnAgregarCartonActionPerformed

    private void btnManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManualActionPerformed

        btnManual.setEnabled(false);
        btnAutomatico.setEnabled(true);
        this.tipoCarton = false;
    }//GEN-LAST:event_btnManualActionPerformed

    private void btnAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutomaticoActionPerformed
        
        btnManual.setEnabled(true);
        btnAutomatico.setEnabled(false);
        this.tipoCarton = true;
    }//GEN-LAST:event_btnAutomaticoActionPerformed

    private void btnSeleccionarModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarModoActionPerformed
        String[] opciones = { "Normal", "Cuatro esquinas", "Cartón lleno" };

        String seleccion = (String) JOptionPane.showInputDialog(
            this,
            "Seleccione el modo de juego:",
            "Modo de juego",
            JOptionPane.PLAIN_MESSAGE,
            null,
            opciones,
            opciones[0]
        );

        if (seleccion == null) return;

        switch (seleccion) {
            case "Normal" ->
                contrlPrin.setModo(ModoJuego.NORMAL);
            case "Cuatro esquinas" ->
                contrlPrin.setModo(ModoJuego.CUATRO_ESQUINAS);
            case "Cartón lleno" ->
                contrlPrin.setModo(ModoJuego.CARTON_LLENO);
        }

        JOptionPane.showMessageDialog(this, "Modo de juego seleccionado: " + seleccion);
    }//GEN-LAST:event_btnSeleccionarModoActionPerformed

    private void btnAgregarCarton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCarton1ActionPerformed
         int ultimo = contrlPrin.getUltimoNumero();

        if (ultimo == -1) {
            JOptionPane.showMessageDialog(this, "Todavía no se ha cantado ningún número.");
        } else {
            JOptionPane.showMessageDialog(this, "El último número cantado es: " + ultimo);
        }
    }//GEN-LAST:event_btnAgregarCarton1ActionPerformed

    private void btnAgregarCarton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCarton2ActionPerformed
         int numero = contrlPrin.sacarNumeroAuto();
        if (numero == -1) {
            JOptionPane.showMessageDialog(this, "Ya no hay más números disponibles.");
            return;
        }
        btnAgregarCarton1.setText("Último Número: " + numero);
        verificarGanadores();
    }//GEN-LAST:event_btnAgregarCarton2ActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
   if (frmTablero.getParent() == null) {
    DesktopJuego.add(frmTablero);
    frmTablero.setVisible(true);
    frmTablero.setLocation(600, 20);
}

// DESPUÉS registrar como observer
contrlPrin.registrarObserver(frmTablero);

    if (frmCartones.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Debe agregar al menos un cartón antes de iniciar.", 
            "Atención", 
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    contrlPrin.reiniciarJuego();
    btnAgregarCarton1.setText("Último Número:");

    JOptionPane.showMessageDialog(this, 
        "Juego iniciado. Presione \"Número\" para cantar bolas.");
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopJuego;
    private javax.swing.JButton btnAgregarCarton;
    private javax.swing.JButton btnAgregarCarton1;
    private javax.swing.JButton btnAgregarCarton2;
    private javax.swing.JButton btnAutomatico;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnManual;
    private javax.swing.JButton btnSeleccionarModo;
    private javax.swing.JLabel imgBolas;
    private javax.swing.JLabel imgCarton;
    private javax.swing.JLabel imgFicha;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
