/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaces;

import Modelo.Carton;
import Modelo.Observer;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author ilope
 */
public class FrmTableroo extends javax.swing.JInternalFrame implements Observer{
private JLabel[] tablero = new JLabel[75];
    /**
     * Creates new form FrmTableroo
     */
    public FrmTableroo() {
        initComponents();
       setLayout(new BorderLayout());
    add(crearTableroBingo(), BorderLayout.CENTER);

    setSize(350, 600);   // tamaño fijo recomendado
    setClosable(false);  // para que no se pueda cerrar
    setIconifiable(false);
    setMaximizable(false);
    setResizable(false);
    setTitle("TABLERO DE BINGO");
    }
private JPanel crearTableroBingo() {
        JPanel panel = new JPanel(new GridLayout(16, 5, 4, 4));

        String[] letras = {"B", "I", "N", "G", "O"};

        for (String letra : letras) {
            JLabel lbl = new JLabel(letra, SwingConstants.CENTER);
            lbl.setFont(lbl.getFont().deriveFont(20f));
            lbl.setOpaque(true);
            lbl.setBackground(new Color(0, 102, 204));
            lbl.setForeground(Color.WHITE);
            lbl.setBorder(BorderFactory.createLineBorder(Color.BLACK));
            panel.add(lbl);
        }

        int n = 1;
        for (int fila = 0; fila < 15; fila++) {
            for (int col = 0; col < 5; col++) {
                JLabel lbl = new JLabel(String.valueOf(n), SwingConstants.CENTER);
                lbl.setOpaque(true);
                lbl.setBackground(Color.WHITE);
                lbl.setBorder(BorderFactory.createLineBorder(Color.BLACK));

                tablero[n - 1] = lbl;
                panel.add(lbl);
                n++;
            }
        }

        return panel;
    }

    public void marcarNumero(int n) {
        if (n < 1 || n > 75) return;
        JLabel lbl = tablero[n - 1];
        lbl.setBackground(Color.YELLOW);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void onNumeroCantado(int numero) {
         marcarNumero(numero);
    }

    @Override
    public void onGanadores(List<Carton> ganadores) {
        repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
